# Generated by Django 4.0.6 on 2022-08-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notiticia',
            new_name='Noticia',
        ),
    ]
