# Generated by Django 4.0.6 on 2022-08-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_rename_notiticia_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='noticia/default.jpg', null=True, upload_to='noticia'),
        ),
    ]
