# Generated by Django 4.0.6 on 2022-08-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0008_noticia_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
