# Generated by Django 4.0.6 on 2022-08-13 04:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0009_alter_noticia_resumen_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, default='noticia/default.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
