# Generated by Django 4.0.6 on 2022-08-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_apellido_remove_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
