# Generated by Django 4.1 on 2022-08-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_first_name_alter_usuario_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
