# Generated by Django 4.0.6 on 2022-08-13 04:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0002_alter_miembro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
