# Generated by Django 4.0.6 on 2022-08-14 07:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0003_alter_miembro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
