# Generated by Django 4.0.6 on 2022-08-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0004_alter_miembro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
