# Generated by Django 4.1 on 2022-08-19 12:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0005_alter_miembro_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
