# Generated by Django 4.0.6 on 2022-08-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_comentario_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha_de_creacion'], 'permissions': (('ver_comentarios', 'Puede ver los comentarios'),), 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
