# Generated by Django 4.0.6 on 2022-08-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0005_rename_fecha_publicacion_comentario_fecha_de_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
