# Generated by Django 4.0.6 on 2022-08-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0007_rename_activo_comentario_aprovado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='aprovado',
            new_name='aprobado',
        ),
    ]
