# Generated by Django 4.1 on 2022-08-19 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0014_alter_noticia_activo_alter_noticia_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentario', '0009_comentario_dislikes_comentario_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(default=True, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='comentario_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='No les gusta'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_de_edicion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comentario_likes', to=settings.AUTH_USER_MODEL, verbose_name='Les gusta'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.noticia', verbose_name='Noticia'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comentario.comentario', verbose_name='Comentario padre'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
